---
--- Generated by Luanalysis
--- Created by jjprices, ep9630.
--- DateTime: 2/4/23 6:58 PM
---

local baseRepoUrl = "https://raw.githubusercontent.com/jjprices/cc-scripts/master/src/"

local function replaceFile(filename)
    shell.run("delete", filename)
    shell.run("wget", baseRepUrl..filename)
end

replaceFile("automine.lua")
replaceFile("update-scripts.lua")